Uncaught Error
MaKu-kodilla/ChatApp pull request #1
Opened 2018-05-26 14:10 UTC by MaKu-kodilla

**https://scr.hu/mGqLL8 -->** 
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat App</title>
  </head>
  <body>
    <div id="app"></div>
    **<script type="text/javascript" src="./bundle.js"></script>**
  </body>
</html>

Z tego co udało mi się znaleźć w necie to powyższy plik może być za to odpowiedzialny, a raczej jakieś jego błędne podpięcie.

Nie mam pomysłu co z tym mogę zrobić. App.boundle.js również próbowałem podpinać i to samo.

2018-05-28 08:12 UTC, michal-bootcamp requested changes
jak poprawisz te rzeczy nizej, to w bledach w konsoli, ktore sie pojawia zwroc uwage na literowki

2018-05-28 08:12 UTC, michal-bootcamp commented on Chat/client/index.js
> +        document.getElementById('root')
podpinasz sie tutaj pod element z id `root`, a w html masz element z id `app`

2018-05-28 08:12 UTC, michal-bootcamp commented on Chat/package.json
> +    "build": "set NODE_ENV=production&webpack",
sprawdz te komende `build` bo teraz nie dziala prawidlowo, poniewaz mimo, ze przekazujesz `production`, webpack generuje wersje `development`

2018-06-02 13:04 UTC, MaKu-kodilla commented
zerkniesz na ten błąd w konsoli?
nie mogę się z nim uporać...

2018-07-07 13:55 UTC, MaKu-kodilla commented
niestety dalej jest jakiś problem, zerkniesz? :)
https://scr.hu/rKvmLg - odpalam to standardowo poprzez npm start na localhost 8080.
Błędy zaczyna wywalać po wpisaniu nickanme.

2018-07-09 14:17 UTC, michal-bootcamp commented
poprawilem literowki i braki: https://github.com/MaKu-kodilla/ChatApp/pull/1/commits/76055d82ae89383814b90cdab7bd85ab1943847b
powinno smigac

Twoje zadanie: popraw sobie skrypt do builda w package.json na wersje windowsowa, wygeneruj builda, odpal serwer przez `node index.js` i sprawdz na localhoscie na dwoch przegladarkach, czy dziala. Jesli bedzie git, to podeslij info

2018-07-12 13:47 UTC, merged